#!/usr/bin/env bash
set -eoux pipefail

db="~/Documents/Dropbox/dotfiles"

brew(){
  brew install \
    ack \
    bash \
    bash-completion \
    clojure \
    docker-machine \
    ffmpeg \
    findutils \
    gcc \
    git \
    gnu-sed \
    gnutls \
    htop \
    gnupg \
    hub \
    jq \
    leiningen \
    netcat \
    node \
    nvm \
    openjdk \
    openssl \
    pinentry \
    pinentry-mac \
    postgresql \
    python3 \
    reattach-to-user-namespace \
    ssh-copy-id \
    telnet \
    tmux \
    tree \
    zip \
    vim \
    yarn \
    youtube-dl
}

user(){
  ln -s ~/Documents/Dropbox/dotfiles/bash/bashrc   ~/.bashrc
  ln -s ~/Documents/Dropbox/dotfiles/bash/profile  ~/.profile
  ln -s ~/Documents/Dropbox/dotfiles/git/gitconfig ~/.gitconfig
  ln -s ~/Documents/Dropbox/dotfiles/git/gitignore ~/.gitignore
  ln -s ~/Documents/Dropbox/dotfiles/bash/aliases  ~/.aliases
  ln -s ~/Documents/Dropbox/dotfiles/bash/fns      ~/.fns
  ln -s ~/Documents/Dropbox/dotfiles/bash/ackrc    ~/.ackrc

  ln -s ~/Documents/Dropbox/dotfiles/bash/ssh-config.sh       ~/.ssh/config
  ln -s ~/Documents/Dropbox/dotfiles/bash/profilelocal-mbp.sh ~/.profilelocal

  ln -s ~/Documents/Dropbox/dotfiles/aws/config      ~/.aws/config
  ln -s ~/Documents/Dropbox/dotfiles/aws/credentials ~/.aws/credentials

  # gpg
  ln -s ~/Documents/Dropbox/dotfiles/gpg/gpg-agent.conf ~/.gnupg/gpg-agent.conf
  ln -s ~/Documents/Dropbox/dotfiles/gpg/gpg.conf       ~/.gnupg/gpg.conf

  # user
  mkdir .vim
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle
  ln -s ~/Documents/Dropbox/dotfiles/vim/vimrc               .vimrc
  ln -s ~/Documents/Dropbox/dotfiles/vim/plugins.vim         .vim/plugins.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/plugin-settings.vim .vim/plugin-settings.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/plugins-osx.vim     .vim/plugins-osx.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/settings.vim        .vim/settings.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/keybindings.vim     .vim/keybindings.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/functions.vim       .vim/functions.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/coc-settings.json   .vim/coc-settings.json
  ~/.vim/bundle/bin/install.sh
  ~/.vim/bundle/bin/neoinstall

  # macOS-personal
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/python.vim  ~/.vim/after/ftplugin/python.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/clojure.vim ~/.vim/after/ftplugin/clojure.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/sh.vim      ~/.vim/after/ftplugin/sh.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/sql.vim     ~/.vim/after/ftplugin/sql.vim

  mkdir ~/.tmux
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ln -s ~/Documents/Dropbox/dotfiles/tmux/tmux.conf ~/.tmux.conf
  ln -s ~/Documents/Dropbox/dotfiles/tmux/keybindings.tmux ~/.tmux/keybindings.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/plugins.tmux ~/.tmux/plugins.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/settings.tmux ~/.tmux/settings.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/theme.tmux ~/.tmux/theme.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/osx.tmux ~/.tmux/osx.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/osx-arm.tmux ~/.tmux/osx-arm.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/linux.tmux ~/.tmux/linux.tmux
  ln -s ~/Documents/Dropbox/dotfiles/tmux/freebsd.tmux ~/.tmux/freebsd.tmux

  mkdir ~/bin
  ln -s ~/Documents/Dropbox/dotfiles/bin/tm ~/bin/tm
}

computer_user() {
  # create dir
  cd ~; mkdir dev; cd dev
  git clone https://github.com/skilbjo/dotfiles.git

  cd ~
  rm .bashrc
  rm .profile
  rm .bash_profile
  rm .gitconfig
  rm .gitignore;
  rm .vimrc
  rm .aliases
  #rm .tmux.conf  ; rm .tmux-osx.conf
  rm .bashrc
  rm .bash_profile

  ln -s ~/dev/dotfiles/bash/bashrc   ~/.bashrc
  ln -s ~/dev/dotfiles/bash/profile  ~/.profile
  ln -s ~/dev/dotfiles/git/gitconfig ~/.gitconfig
  ln -s ~/dev/dotfiles/git/gitignore ~/.gitignore
  ln -s ~/dev/dotfiles/bash/aliases  ~/.aliases
  ln -s ~/dev/dotfiles/bash/fns      ~/.fns
  ln -s ~/dev/dotfiles/bash/ackrc    ~/.ackrc

  ln -s ~/Documents/Dropbox/dotfiles/bash/ssh-config.sh       ~/.ssh/config
  ln -s ~/Documents/Dropbox/dotfiles/bash/profilelocal-mbp.sh ~/.profilelocal

  ln -s ~/Documents/Dropbox/dotfiles/aws/config      ~/.aws/config
  ln -s ~/Documents/Dropbox/dotfiles/aws/credentials ~/.aws/credentials

  # gpg
  ln -s ~/Documents/Dropbox/dotfiles/gpg/gpg-agent.conf gpg-agent.conf

  # user
  mkdir .vim
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle
  ln -s ~/dev/dotfiles/vim/vimrc               .vimrc
  ln -s ~/dev/dotfiles/vim/plugins.vim         .vim/plugins.vim
  ln -s ~/dev/dotfiles/vim/plugin_settings.vim .vim/plugin_settings.vim
  ln -s ~/dev/dotfiles/vim/settings.vim        .vim/settings.vim
  ln -s ~/dev/dotfiles/vim/keybindings.vim     .vim/keybindings.vim
  ln -s ~/dev/dotfiles/vim/functions.vim       .vim/functions.vim
  ~/.vim/bundle/bin/install.sh
  ~/.vim/bundle/bin/neoinstall

  # Arch Linux
  ln -s ~/dev/dotfiles/vim/after/ftplugin/python.vim .vim/after/ftplugin/python.vim
  ln -s ~/dev/dotfiles/vim/after/ftplugin/clojure.vim .vim/after/ftplugin/clojure.vim
  # macOS-work
  ln -s ~/Dropbox/dotfiles/vim/after/ftplugin/python.vim ~/.vim/after/ftplugin/python.vim
  ln -s ~/Dropbox/dotfiles/vim/after/ftplugin/clojure.vim ~/.vim/after/ftplugin/clojure.vim
  # macOS-personal
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/python.vim ~/.vim/after/ftplugin/python.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/clojure.vim ~/.vim/after/ftplugin/clojure.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/sh.vim ~/.vim/after/ftplugin/sh.vim
  ln -s ~/Documents/Dropbox/dotfiles/vim/after/ftplugin/sql.vim ~/.vim/after/ftplugin/sql.vim

  mkdir ~/.tmux
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ln -s ~/dev/dotfiles/tmux/tmux.conf ~/.tmux.conf
  ln -s ~/dev/dotfiles/tmux/keybindings.tmux ~/.tmux/keybindings.tmux
  ln -s ~/dev/dotfiles/tmux/plugins.tmux ~/.tmux/plugins.tmux
  ln -s ~/dev/dotfiles/tmux/settings.tmux ~/.tmux/settings.tmux
  ln -s ~/dev/dotfiles/tmux/theme.tmux ~/.tmux/theme.tmux
  ln -s ~/dev/dotfiles/tmux/osx.tmux ~/.tmux/osx.tmux
  ln -s ~/dev/dotfiles/tmux/linux.tmux ~/.tmux/linux.tmux
  ln -s ~/dev/dotfiles/tmux/freebsd.tmux ~/.tmux/freebsd.tmux

  mkdir ~/bin
  ln -s ~/dev/dotfiles/bin/tm ~/bin/tm
}

debian(){
  cd ~

  # the goods
  sudo apt install -y bash bash-completion jq htop python3-pip
  pip3 install awscli --user --upgrade

  # tmux
  sudo apt install -y automake build-essential pkg-config libevent-dev libcurses5-dev

  # tmux
  git clone https://github.com/tmux/tmux.git
  cd tmux
  sh autogen.sh
  (./configure && make)
  sleep 5
  cd ~/tmux
  mkdir ~/bin
  mv tmux ~/bin/
}

mesos(){
  # bring over dotfiles
  sudo yum -y install git automake ncurses-devel glibc-static

  cd ~; mkdir dev; cd dev;
  git clone https://github.com/skilbjo/dotfiles.git

  # libevent
  wget https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz
  tar xzvf libevent-2.0.21-stable.tar.gz
  cd libevent-2.0.21-stable
  ./configure && make
  sudo make install
  cd ~

  # tmux
  git clone https://github.com/tmux/tmux.git
  cd tmux
  sh autogen.sh
  (./configure && make)
  sleep 5
  cd ~/tmux
  mkdir ~/bin
  mv tmux ~/bin/

  # tmux dotfiles
  cd ~
  mkdir ~/.tmux
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ln -s ~/dev/dotfiles/tmux/tmux.conf ~/.tmux.conf
  ln -s ~/dev/dotfiles/tmux/keybindings.tmux ~/.tmux/keybindings.tmux
  ln -s ~/dev/dotfiles/tmux/plugins.tmux ~/.tmux/plugins.tmux
  ln -s ~/dev/dotfiles/tmux/settings.tmux ~/.tmux/settings.tmux
  ln -s ~/dev/dotfiles/tmux/theme.tmux ~/.tmux/theme.tmux
  ln -s ~/dev/dotfiles/tmux/osx.tmux ~/.tmux/osx.tmux
  ln -s ~/dev/dotfiles/tmux/linux.tmux ~/.tmux/linux.tmux
  ln -s ~/dev/dotfiles/tmux/freebsd.tmux ~/.tmux/freebsd.tmux

  ln -s ~/dev/dotfiles/bin/tm ~/bin/tm

  export PATH='/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:~/bin'

  cd ~; mkdir dev; cd dev
  git clone https://github.com/skilbjo/dotfiles.git
  cd ~; mkdir .vim
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle
  ln -s ~/dev/dotfiles/vim/vimrc .vimrc
  ln -s ~/dev/dotfiles/vim/plugins.vim .vim/plugins.vim
  ln -s ~/dev/dotfiles/vim/plugin_settings.vim .vim/plugin_settings.vim
  ln -s ~/dev/dotfiles/vim/settings.vim .vim/settings.vim
  ln -s ~/dev/dotfiles/vim/keybindings.vim .vim/keybindings.vim
  ln -s ~/dev/dotfiles/vim/functions.vim .vim/functions.vim
  ~/.vim/bundle/bin/install.sh
  ~/.vim/bundle/bin/neoinstall
}

root() {
  # root
  cd ~/dev/dotfiles && git pull
  sudo -s
  cd ~
  ln -s /home/skilbjo/dev/dotfiles/bash/bashrc .bashrc
  ln -s /home/skilbjo/dev/dotfiles/bash/profile .profile
  ln -s /home/skilbjo/dev/dotfiles/bash/aliases .aliases
  mkdir .vim
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle
  ln -s /home/skilbjo/dev/dotfiles/vim/vimrc .vimrc
  ln -s /home/skilbjo/dev/dotfiles/vim/plugins.vim .vim/plugins.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/plugin_settings.vim .vim/plugin_settings.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/settings.vim .vim/settings.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/keybindings.vim .vim/keybindings.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/functions.vim .vim/functions.vim
  ~/.vim/bundle/bin/install.sh
  ~/.vim/bundle/bin/neoinstall
}

function bash {
  ln -s $db/bash/bashrc ~/.bashrc
  ln -s $db/bash/profile ~/.profile
  ln -s $db/bash/aliases ~/.aliases
}

function git {
  ln -s $db/git/gitconfig ~/.gitconfig
  ln -s $db/git/gitignore ~/.gitignore
}

function vim {
  ln -s $db/vim/vimrc ~/.vimrc
  mkdir ~/.vim
  ln -s $db/vim/plugins.vim ~/.vim/plugins.vim
  ln -s $db/vim/plugin_settings.vim ~/.vim/plugin_settings.vim
  ln -s $db/vim/settings.vim ~/.vim/settings.vim
  ln -s $db/vim/keybindings.vim ~/.vim/keybindings.vim
  ln -s $db/vim/functions.vim ~/.vim/functions.vim
}

function lein {
  ln -s $db/lein ~/.lein
}

function tmux {
  ln -s $db/tmux/tmux.conf ~/.tmux.conf
  ln -s $db/tmux/tmux.conf ~/.tmux-osx.conf
  ln -s $db/tmux/osx.tmux ~/.tmux/osx.tmux
  ln -s $db/tmux/keybindings.tmux keybindings.tmux
  ln -s $db/tmux/settings.tmux settings.tmux
  ln -s $db/tmux/theme.tmux theme.tmux
  ln -s $db/tmux/plugins.tmux plugins.tmux
}

function sublime_text {
  echo "/Users/john.skilbeck/Library/Application Support/Sublime Text 3/Packages/User"
}


remove_existing
bash
git
vim
lein
tmux

exit
