#!/usr/bin/env bash

: ${APP_NAME:='app-name-here'}
: ${DOCKER_REGISTRY:='quay.io'}
: ${DOCKER_REMOTE:='quay.io/skilbjo/$APP_NAME'}

tag=$1
cmd=$2

if [[ $# -eq 0 ]]; then
  docker run -it "$DOCKER_REMOTE" /bin/bash
else
  docker run -it "$DOCKER_REMOTE":$1 /bin/bash
fi
