#!/usr/bin/env bash
set -eoux pipefail

install_packages(){
  sudo yum update -y

  # docker?
  sudo yum install -y git bash postgresql
}

aws_cli(){
  mkdir -p ~/bin
  curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  unzip awscli-bundle.zip
  ./awscli-bundle/install -b ~/bin/aws
}

get_java_key_store(){
  cd ~
  aws s3 cp s3://skilbjo/java_key_store java_key_store
}

deploy_dir(){
  cd ~; mkdir deploy; cd deploy;
  mkdir -p app ; cd app;

  # compojure
  git clone git@github.com:skilbjo/compojure.git
  sudo cp compojure/deploy/tasks/crontab /etc/cron.d
  # duckdns
  git clone git@github.com:skilbjo/duckdns.git
  sudo cp duckdns/deploy/tasks/crontab /etc/cron.d
}

dotfiles(){
  cd ~; mkdir dev; cd dev;
  git clone https://github.com/skilbjo/dotfiles.git

  cd ~
  rm .bashrc
  rm .profile
  rm .bash_profile
  rm .gitconfig
  rm .gitignore;
  rm .vimrc
  rm .aliases
  #rm .tmux.conf  ; rm .tmux-osx.conf
  rm .bashrc
  rm .bash_profile

  ln -s ~/dev/dotfiles/bash/bashrc       .bashrc
  ln -s ~/dev/dotfiles/bash/profile      .profile
  ln -s ~/dev/dotfiles/git/gitconfig     .gitconfig
  ln -s ~/dev/dotfiles/git/gitignore     .gitignore
  ln -s ~/dev/dotfiles/bash/aliases      .aliases
  ln -s ~/dev/dotfiles/bash/aliases-work .aliases-work

  # user
  mkdir .vim
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle
  ln -s ~/dev/dotfiles/vim/vimrc .vimrc
  ln -s ~/dev/dotfiles/vim/plugins.vim .vim/plugins.vim
  ln -s ~/dev/dotfiles/vim/plugin_settings.vim .vim/plugin_settings.vim
  ln -s ~/dev/dotfiles/vim/settings.vim .vim/settings.vim
  ln -s ~/dev/dotfiles/vim/keybindings.vim .vim/keybindings.vim
  ln -s ~/dev/dotfiles/vim/functions.vim .vim/functions.vim
  ~/.vim/bundle/bin/install.sh
  ~/.vim/bundle/bin/neoinstall

  # tmux
  git clone https://github.com/tmux/tmux.git
  cd tmux
  sh autogen.sh
  ./configure && make
  cd ~/tmux/
  mv tmux ~/bin/

  # tmux dotfiles
  cd ~
  mkdir ~/.tmux
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ln -s ~/dev/dotfiles/tmux/tmux.conf ~/.tmux.conf
  ln -s ~/dev/dotfiles/tmux/keybindings.tmux ~/.tmux/keybindings.tmux
  ln -s ~/dev/dotfiles/tmux/plugins.tmux ~/.tmux/plugins.tmux
  ln -s ~/dev/dotfiles/tmux/settings.tmux ~/.tmux/settings.tmux
  ln -s ~/dev/dotfiles/tmux/theme.tmux ~/.tmux/theme.tmux
  ln -s ~/dev/dotfiles/tmux/osx.tmux ~/.tmux/osx.tmux
  ln -s ~/dev/dotfiles/tmux/linux.tmux ~/.tmux/linux.tmux
  ln -s ~/dev/dotfiles/tmux/freebsd.tmux ~/.tmux/freebsd.tmux

  mkdir ~/bin
  ln -s ~/dev/dotfiles/bin/tm ~/bin/tm
}

port_forwarding(){
  sudo iptables -t nat -A PREROUTING -p tcp --dport 80  -j REDIRECT --to-ports 8080
  sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
}

root(){
  # root
  cd ~/dev/dotfiles && git pull
  sudo -s
  cd ~
  ln -s /home/skilbjo/dev/dotfiles/bash/bashrc .bashrc
  ln -s /home/skilbjo/dev/dotfiles/bash/profile .profile
  ln -s /home/skilbjo/dev/dotfiles/bash/aliases .aliases
  mkdir .vim
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle
  ln -s /home/skilbjo/dev/dotfiles/vim/vimrc .vimrc
  ln -s /home/skilbjo/dev/dotfiles/vim/plugins.vim .vim/plugins.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/plugin_settings.vim .vim/plugin_settings.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/settings.vim .vim/settings.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/keybindings.vim .vim/keybindings.vim
  ln -s /home/skilbjo/dev/dotfiles/vim/functions.vim .vim/functions.vim
  ~/.vim/bundle/bin/install.sh
  ~/.vim/bundle/bin/neoinstall
}
