#!/usr/bin/env bash
# -- docs -------------------------------------------------------
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# -- path, command prompt ---------------------------------------
export PS1="\W λ "

# -- computer-specific stuffs -----------------------------------
# Work specific pem keys (place pem keys in ~/.ssh
work() {
	for file in $(ls ~/.ssh/*.pem); do 
		ssh-add $file > /dev/null 2>&1;
	done
}

computer_specific() {
	case $(whoami) in
		('john.skilbeck') work;;
		(skilbjo) ;; 
	esac
}

computer_specific

