#!/usr/bin/env bash
set -u

# If not running interactively, don't do anything
[[ $- == *i* ]] || return

# -- docs -------------------------------------------------------
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# -- use color vars below ---------------------------------------
# colors:$ for i in $(seq 0 7); do tput setaf $i && echo "$i - color"; done
if [[ $- == *i* ]]; then
  black="\[$(tput setaf 0)\]"
  red="\[$(tput setaf 1)\]"
  green="\[$(tput setaf 2)\]"
  yellow="\[$(tput setaf 3)\]"
  blue="\[$(tput setaf 4)\]"
  pink="\[$(tput setaf 5)\]"
  teal="\[$(tput setaf 6)\]"
  grey="\[$(tput setaf 7)\]"
  off="\[$(tput sgr0)\]"
  bold="\[01;32m"
fi

linux() {
  eval "$(keychain --eval /home/skilbjo/.ssh/id_rsa)"
}

freebsd() {
  eval "$(keychain --eval /home/skilbjo/.ssh/id_rsa)"
}

os_specific() {
  case $(uname) in
    ('Linux')
      case $(uname -a) in
        *amzn*) ;;
        *) linux ;;
      esac ;;
    ('FreeBSD') freebsd ;;
  esac
}

os_specific

# -- computer-specific stuffs -----------------------------------
skilbjo() {
  # -- path, command prompt ---------------------------------------
  export PS1="${red}@\h${off}:${yellow}\W ${off}$ "
  #export PS1='[\u@\h \W]\$ '
  #export PS1="\W λ "

  export JAVA_HOME=$(/usr/libexec/java_home -v 1.8) # Java 1.8
}

work() {
  # -- path, command prompt ---------------------------------------
  export PS1="${red}@\h${off}:${yellow}\W ${off}$ "

  # Add password-protected id_rsa key
  ssh-add -K ~/.ssh/id_rsa || (eval "$(ssh-agent -s)" && ssh-add -K ~/.ssh/id_rsa)

  #export JAVA_HOME=$(/usr/libexec/java_home -v 10) # Java 10
  #export JAVA_HOME=$(/usr/libexec/java_home -v 9) # Java 9
  export JAVA_HOME=$(/usr/libexec/java_home -v 1.8) # Java 1.8
}

root() {
  #[root@pi1 ~]# exit
  export PS1="[${black}\u@\h:${yellow}\W ${off}]# "

  bind 'set show-all-if-ambiguous on'
  bind 'TAB:menu-complete'
  bind 'set completion-ignore-case on'
  bind 'set visible-stats on'
  bind 'set page-completions off'

  set +u
}

_aws() {
  # -- path, command prompt ---------------------------------------
  export PS1="${red}@\h${off}:${yellow}\W ${off}$ "
  #export PS1='[\u@\h \W]\$ '
  #export PS1="\W λ "
}

computer_specific() {
  case $(whoami) in
    ('john.skilbeck') work ;;
    ('johnskilbeck') work ;;
    (skilbjo) skilbjo ;;
    (root) root ;;
    (ec2-user) _aws;;
  esac
}

computer_specific
