#!/usr/bin/env bash
set -u

# -- docs -------------------------------------------------------
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# -- use color vars below ---------------------------------------
# colors:$ for i in $(seq 0 7); do tput setaf $i && echo "$i - color"; done
if [[ $- == *i* ]]; then
  black="\[$(tput setaf 0)\]"
  red="\[$(tput setaf 1)\]"
  green="\[$(tput setaf 2)\]"
  yellow="\[$(tput setaf 3)\]"
  blue="\[$(tput setaf 4)\]"
  pink="\[$(tput setaf 5)\]"
  teal="\[$(tput setaf 6)\]"
  grey="\[$(tput setaf 7)\]"
  off="\[$(tput sgr0)\]"
  bold="\[01;32m"
fi

linux() {
  eval "$(keychain --eval id_rsa)"
}

os_specific() {
  case $(uname) in
    ('Linux') linux;;
  esac
}

os_specific

# -- computer-specific stuffs -----------------------------------
skilbjo() {
  # -- path, command prompt ---------------------------------------
  export PS1="${red}@\h${off}:${yellow}\W ${off}$ "
  #export PS1='[\u@\h \W]\$ '
  #export PS1="\W λ "
}

work() {
  # -- path, command prompt ---------------------------------------
  export PS1="${red}@\h${off}:${yellow}\W ${off}$ "

  # Add pem files to keychain
  for file in $(ls ~/.ssh/*.pem); do
    ssh-add $file > /dev/null 2>&1;
  done

  # Add password-protected id_rsa key
  ssh-add ~/.ssh/id_rsa #>/dev/null 2>&1
}

root() {
  #[root@pi1 ~]# exit
  export PS1="[${black}\u@\h:${yellow}\W ${off}]# "
}

computer_specific() {
  case $(whoami) in
    ('john.skilbeck') work ;;
    (skilbjo) skilbjo ;;
    (root) root ;;
  esac
}

computer_specific

