#!/usr/bin/env bash
set -u

# -- general ----------------------------------------------------
kmsd(){
  # https://stackoverflow.com/a/53735748/2490091
  # call it like: `pbpaste | kmsd`
  aws kms decrypt \
    --profile personal \
    --ciphertext-blob fileb://<( \
      cat /dev/stdin | \
      sed 's/.*kmscrypt:://' | \
      tr -d '\n' | \
      base64 -D
    ) \
    --output text \
    --key-id "$aws_kms_key" \
    --region us-east-1 \
    --query Plaintext | \
  base64 -D
}

kmse(){
  # https://stackoverflow.com/a/53735748/2490091
  # call it like: `pbpaste | kmse`
  aws kms encrypt \
    --profile personal \
    --key-id "$aws_kms_key" \
    --plaintext "$(cat /dev/stdin)" \
    --region us-east-1 \
    --query CiphertextBlob \
    --output text
}

git() {
  if [[ $@ == 'push -f'* ]] || [[ $@ == 'pu -f'* ]]; then
    echo 'use --force-with-lease instead'
  else
    command git "$@"
  fi
}

# -- ai ---------------------------------------------------------
ask() {
  local user_prompt="$*"
  local system_prompt='Respond concisely and in plain text only, no markdown formatting or special characters'

  local model='google/gemini-2.0-flash-exp:free'
  local model='deepseek/deepseek-chat-v3-0324:free'
  local model='meta-llama/llama-4-scout:free'

  local model_to_use="$model"
  local result=$(curl -s https://openrouter.ai/api/v1/chat/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENROUTER_API_KEY" \
    -d '{
      "model": "'"${model_to_use}"'",
      "messages": [
        {
          "role": "system",
          "content": [
            {
              "type": "text",
              "text": "'"${system_prompt//\"/\\\"}"'"
            }
          ]
        },
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "'"${user_prompt//\"/\\\"}"'"
            }
          ]
        }
      ]
    }')
  local answer="$(echo $result | jq -r '.choices[0].message.content')"
  # echo "$result"
  echo "$answer"
}

# -- work -------------------------------------------------------
logs(){
  local log_group_name="$1"
  local log_stream_name="$2"

  log_group_name='/aws/lambda/platform-txn-CounselorSer-ServiceSqsHandleTransact-QRF9BTCXUTXZ'
  log_stream_name='2020/07/02/[$LATEST]7ffab4e9f53e4a8f992d3edcaf9aef3f'

  aws --profile xhrdev --region us-east-1 \
    logs \
    get-log-events \
    --log-group-name "$log_group_name" \
    --log-stream-name "$log_stream_name"
}

query_logs(){
  local date="$1"
  local start="$(gdate --date "$date - 2 minute" +%s)"
  local end="$(gdate --date "$date + 2 minute" +%s)"
    #--start-time "$start" \
    #--end-time "$end" \
  local log_group_name='/aws/lambda/platform-txn-CounselorSer-ServiceSqsHandleTransact-QRF9BTCXUTXZ'
  local query='fields @message like /error/'
  local query='fields @timestamp, @message | sort @timestamp desc | limit 20'

  log_group_name='/aws/lambda/platform-txn-CounselorSer-ServiceSqsHandleTransact-QRF9BTCXUTXZ'
  query='fields @timestamp, @message | sort @timestamp desc | limit 20'
  query_id="$(aws --profile xhrdev --region us-east-1 \
    logs \
    start-query \
    --start-time 1593736067 \
    --end-time 1593736313 \
    --log-group-name "$log_group_name" \
    --query-string "$query" | jq '.queryId')"

  aws --profile xhrdev --region us-east-1 \
    logs \
    get-query-results \
    --query-id "$query_id"
}

assume-role(){
  local acct="$1"
  local role_name="$2"
  local duration=${3:-3600}

  aws-mfa --duration "$duration" --profile "$acct" --assume-role "$("${EISH_HOME}/si-role-arn" -n "$acct" -r "$role_name")"
}

assume-aws-dev(){
  assume-role xhrdev 43200
}

assume-aws-build(){
  assume-role xhrdev ro 14400
}

assume-aws-build-wheel(){
  assume-role xhrdev wheel 3600
}

assume-aws-prod(){
  assume-role xhrdev ro 14400
}

assume-aws-prod-wheel(){
  assume-role xhrdev wheel 3600
}

## google cloud
gcp-psql(){
  psql "sslmode=verify-ca sslrootcert=/Users/skilbjo/Downloads/server-ca.pem \
      sslcert=/Users/skilbjo/client-cert.pem sslkey=/Users/skilbjo/Downloads/client-key.pem \
      hostaddr=35.193.230.82 \
      port=5432 \
      user=postgres dbname=postgres"
}

sso(){
  unset AWS_PROFILE
  export AWS_PROFILE=$1
  aws sts get-caller-identity &> /dev/null || aws sso login || (unset AWS_PROFILE && aws-configure-sso-profile --profile $1)
  eval $(aws-export-credentials --env-export)
}


# -- work0 ------------------------------------------------------
uri-encode() {
  # uri-encode <string>
  old_lc_collate=$LC_COLLATE
  LC_COLLATE=C

  local length="${#1}"
  for (( i = 0; i < length; i++ )); do
    local c="${1:$i:1}"
    case $c in
      [a-zA-Z0-9.~_-])
        printf '%s' "$c" ;;
      *)
        printf '%%%02X' "'$c" ;;
    esac
  done
  echo ''

  LC_COLLATE=$old_lc_collate
}

uri-decode() {
  # uri-decode <string>
  local url_encoded="${1//+/ }"
  printf '%b' "${url_encoded//%/\\x}"
  echo ''
}

# https://github.com/nvm-sh/nvm#automatically-call-nvm-use
cdnvm() {
  cd "$@";
  nvm_path="$(nvm_find_up .nvmrc | tr -d '\n')"
  entry_version="$(node --version)"

  # If there are no .nvmrc file, use the default nvm version
  if [[ ! $nvm_path = *[^[:space:]]* ]]; then
    local default_version=$(nvm version default);
    local nvm_version=$(<"$nvm_path"/.nvmrc)

    if [[ $entry_version != $nvm_version ]]; then
      nvm use "$nvm_version";
    fi
  else
    local nvm_version=$(<"$nvm_path"/.nvmrc)

    if [[ $entry_version != $nvm_version ]]; then
      # echo "$entry_version"
      # echo "$nvm_version"
      # echo [[ $entry_version != $nvm_version ]]
      nvm use "$nvm_version";
    fi
  fi
}

alias cd='cdnvm'
cd $PWD
