#!/usr/bin/env bash
set -u

assume-role(){
  local acct="$1"
  local role_name="$2"
  local duration=${3:-3600}

  aws-mfa --duration "$duration" --profile "$acct" --assume-role "$("${EISH_HOME}/si-role-arn" -n "$acct" -r "$role_name")"
}

switch-to-aws-dev(){
  assume-role stedi/dev wheel 43200
}

switch-role(){
  local acct="$1"
  local role="$1"
  "${EISH_HOME}/si-switchrole-url" -n "$acct" -r "$role"
}

kmsd(){
  # https://stackoverflow.com/a/53735748/2490091
  aws kms decrypt \
    --profile skilbjo \
    --ciphertext-blob fileb://<( \
      cat /dev/stdin | \
      sed 's/.*kmscrypt:://' | \
      tr -d '\n' | \
      base64 -D
    ) \
    --output text \
    --key-id "$aws_kms_key" \
    --region us-east-1 \
    --query Plaintext | \
  base64 -D
}

kmse(){
  # https://stackoverflow.com/a/53735748/2490091
  aws kms encrypt \
    --profile skilbjo \
    --key-id "$aws_kms_key" \
    --plaintext "$(cat /dev/stdin)" \
    --region us-east-1 \
    --query CiphertextBlob \
    --output text
}
